import json

path = r'g:\Code\Deep Learning\ETTForecasting\35_Report_Model.ipynb'
with open(path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

for cell in nb['cells']:
    if cell['cell_type'] == 'code':
        source = cell['source']
        if 'def predict_informer' in ''.join(source):
            cell['source'] = [
                'def predict_informer(model, test_loader, scaler, target_idx, device):\n',
                '    \"\"\"Load best checkpoint and run prediction on test set.\"\"\"\n',
                '    model.load_state_dict(torch.load(cfg.INF_CKPT, map_location=device))\n',
                '    model.eval()\n',
                '\n',
                '    preds_list, trues_list = [], []\n',
                '    with torch.no_grad():\n',
                '        for enc_x, dec_y, enc_mark, dec_mark in test_loader:\n',
                '            enc_x    = enc_x.float().to(device)\n',
                '            dec_y_f  = dec_y.float()\n',
                '            enc_mark = enc_mark.float().to(device)\n',
                '            dec_mark = dec_mark.float().to(device)\n',
                '\n',
                '            # Decoder input: [label_len history | zero padding]\n',
                '            # Use ALL 7 features for Decoder input\n',
                '            pred_pad = torch.zeros([dec_y_f.shape[0], cfg.PRED_LEN, dec_y_f.shape[-1]]).float()\n',
                '            # Inject future sin/cos (last 2 columns)\n',
                '            pred_pad[:, :, -2:] = dec_y_f[:, -cfg.PRED_LEN:, -2:]\n',
                '            \n',
                '            dec_inp = torch.cat([dec_y_f[:, :cfg.LABEL_LEN, :], pred_pad], dim=1).float().to(device)\n',
                '\n',
                '            out = model(enc_x, enc_mark, dec_inp, dec_mark)  # (B, pred_len, 1)\n',
                '            gt  = dec_y_f[:, -cfg.PRED_LEN:, target_idx:target_idx+1]\n',
                '\n',
                '            preds_list.append(out.squeeze(-1).cpu().numpy())\n',
                '            trues_list.append(gt.squeeze(-1).cpu().numpy())\n',
                '\n',
                '    preds = np.concatenate(preds_list, axis=0)\n',
                '    trues = np.concatenate(trues_list, axis=0)\n',
                '    preds = preds * scaler.scale_[target_idx] + scaler.mean_[target_idx]\n',
                '    trues = trues * scaler.scale_[target_idx] + scaler.mean_[target_idx]\n',
                '    return preds, trues\n',
                '\n',
                'inf_preds, inf_trues = predict_informer(informer_model, test_loader_inf, scaler, target_idx, device)\n',
                'inf_metrics = metric(inf_preds, inf_trues)\n',
                'print(\"Informer Test Metrics:\")\n',
                'for k, v in inf_metrics.items():\n',
                '    print(f\"  {k}: {v:.4f}\")'
            ]
        elif 'def demo_predict_informer' in ''.join(source):
            cell['source'] = [
                'import random as _random\n',
                '\n',
                'def demo_predict_seq2seq(model, test_scaled, scaler, target_idx, device, sample_idx=None):\n',
                '    \"\"\"Predict a single sample from test set using Seq2Seq.\"\"\"\n',
                '    ds = TimeSeriesDataset4Seq(test_scaled, cfg.SEQ_LEN, cfg.PRED_LEN)\n',
                '    if sample_idx is None:\n',
                '        sample_idx = _random.randint(0, len(ds) - 1)\n',
                '\n',
                '    X, Y = ds[sample_idx]\n',
                '    X = X.unsqueeze(0).to(device)\n',
                '    Y = Y.unsqueeze(0).to(device)\n',
                '\n',
                '    model.load_state_dict(torch.load(cfg.S2S_CKPT, map_location=device))\n',
                '    model.eval()\n',
                '    with torch.no_grad():\n',
                '        # Future features: only sin/cos (last 2 columns)\n',
                '        future_feat = Y[:, :, -2:]\n',
                '        pred = model(X, y=None, future_features=future_feat, teacher_forcing_ratio=0.0)\n',
                '\n',
                '    pred_real = pred.cpu().numpy().flatten() * scaler.scale_[target_idx] + scaler.mean_[target_idx]\n',
                '    true_real = Y[:, :, target_idx].cpu().numpy().flatten() * scaler.scale_[target_idx] + scaler.mean_[target_idx]\n',
                '    return pred_real, true_real, sample_idx\n',
                '\n',
                '\n',
                'def demo_predict_informer(model, test_scaled, test_index, scaler, target_idx, device, sample_idx=None):\n',
                '    \"\"\"Predict a single sample from test set using Informer.\"\"\"\n',
                '    ds = ETTDatasetInformer(test_scaled, test_index, cfg.SEQ_LEN, cfg.LABEL_LEN, cfg.PRED_LEN)\n',
                '    if sample_idx is None:\n',
                '        sample_idx = _random.randint(0, len(ds) - 1)\n',
                '\n',
                '    enc_x, dec_y, enc_mark, dec_mark = ds[sample_idx]\n',
                '    enc_x    = enc_x.unsqueeze(0).float().to(device)\n',
                '    dec_y_f  = dec_y.unsqueeze(0).float()\n',
                '    enc_mark = enc_mark.unsqueeze(0).float().to(device)\n',
                '    dec_mark = dec_mark.unsqueeze(0).float().to(device)\n',
                '\n',
                '    pred_pad = torch.zeros([1, cfg.PRED_LEN, dec_y_f.shape[-1]]).float()\n',
                '    # Inject future sin/cos (last 2 columns)\n',
                '    pred_pad[:, :, -2:] = dec_y_f[:, -cfg.PRED_LEN:, -2:]\n',
                '    \n',
                '    dec_inp = torch.cat([dec_y_f[:, :cfg.LABEL_LEN, :], pred_pad], dim=1).float().to(device)\n',
                '\n',
                '    model.load_state_dict(torch.load(cfg.INF_CKPT, map_location=device))\n',
                '    model.eval()\n',
                '    with torch.no_grad():\n',
                '        out = model(enc_x, enc_mark, dec_inp, dec_mark)\n',
                '\n',
                '    pred_real = out.squeeze(-1).cpu().numpy().flatten() * scaler.scale_[target_idx] + scaler.mean_[target_idx]\n',
                '    gt = dec_y_f[:, -cfg.PRED_LEN:, target_idx]\n',
                '    true_real = gt.cpu().numpy().flatten() * scaler.scale_[target_idx] + scaler.mean_[target_idx]\n',
                '    return pred_real, true_real, sample_idx\n',
                '\n',
                '# Run demo \n',
                'idx = _random.randint(0, len(test_ds_seq) - 1)\n',
                's2s_p, s2s_t, _ = demo_predict_seq2seq(seq2seq_model, test_scaled, scaler, target_idx, device, idx)\n',
                'inf_p, inf_t, _ = demo_predict_informer(informer_model, test_scaled, test_df.index, scaler, target_idx, device, idx)\n',
                '\n',
                'fig, axes = plt.subplots(1, 2, figsize=(16, 5))\n',
                'axes[0].plot(s2s_t, \"o-\", label=\"True\", markersize=4)\n',
                'axes[0].plot(s2s_p, \"x--\", label=\"Seq2Seq Pred\", markersize=4)\n',
                'axes[0].set_title(f\"Seq2Seq - Sample #{idx}\")\n',
                'axes[0].legend(); axes[0].grid(True)\n',
                '\n',
                'axes[1].plot(inf_t, \"o-\", label=\"True\", markersize=4)\n',
                'axes[1].plot(inf_p, \"x--\", label=\"Informer Pred\", markersize=4)\n',
                'axes[1].set_title(f\"Informer - Sample #{idx}\")\n',
                'axes[1].legend(); axes[1].grid(True)\n',
                '\n',
                'plt.tight_layout()\n',
                'plt.show()\n',
                '\n',
                'print(f\"\\nSample #{idx}\")\n',
                'print(f\"Seq2Seq  MAE: {np.mean(np.abs(s2s_p - s2s_t)):.4f}\")\n',
                'print(f\"Informer MAE: {np.mean(np.abs(inf_p - inf_t)):.4f}\")\n'
            ]
        elif 'data/test_data.xlsx' in ''.join(source):
            cell['source'] = [
                'import pandas as pd\n',
                'import numpy as np\n',
                'import torch\n',
                'import matplotlib.pyplot as plt\n',
                'from src.data.preprocessing import load_and_split, add_time_features\n',
                '\n',
                '# 1. Load custom test data (test_data.xlsx has 96 rows)\n',
                'test_custom = pd.read_excel(\"data/test_data.xlsx\")\n',
                'test_custom[\"date\"] = pd.to_datetime(test_custom[\"date\"])\n',
                'test_custom.set_index(\"date\", inplace=True)\n',
                '\n',
                '# 2. Drop columns\n',
                'if hasattr(cfg, \"DROP_COLS\") and cfg.DROP_COLS:\n',
                '    test_custom = test_custom.drop(columns=cfg.DROP_COLS, errors=\"ignore\")\n',
                '\n',
                '# 3. Add time features\n',
                'test_custom = add_time_features(test_custom)\n',
                '\n',
                '# 4. Scale\n',
                'test_custom_scaled = scaler.transform(test_custom.values)\n',
                '\n',
                '# 5. Prepare tensor (1 batch, seq_len=96, features=7)\n',
                'X_custom = torch.tensor(test_custom_scaled, dtype=torch.float32).unsqueeze(0).to(device)\n',
                '\n',
                '# 6. Initialize future features (sin/cos)\n',
                'last_date = test_custom.index[-1]\n',
                'future_dates = pd.date_range(start=last_date + pd.Timedelta(minutes=15), periods=cfg.PRED_LEN, freq=\"15min\")\n',
                'future_df = pd.DataFrame(index=future_dates)\n',
                'future_df[\"dummy\"] = 0\n',
                'future_df = add_time_features(future_df)\n',
                '\n',
                'Y_custom_dummy = torch.zeros((1, cfg.PRED_LEN, 2), device=device)\n',
                'Y_custom_dummy[0, :, 0] = torch.tensor(future_df[\"time_sin\"].values, dtype=torch.float32).to(device)\n',
                'Y_custom_dummy[0, :, 1] = torch.tensor(future_df[\"time_cos\"].values, dtype=torch.float32).to(device)\n',
                '\n',
                'future_feat = Y_custom_dummy\n',
                '\n',
                '# 7. Predict\n',
                'seq2seq_model.load_state_dict(torch.load(cfg.S2S_CKPT, map_location=device))\n',
                'seq2seq_model.eval()\n',
                'with torch.no_grad():\n',
                '    out = seq2seq_model(X_custom, y=None, future_features=future_feat, teacher_forcing_ratio=0.0)\n',
                '\n',
                'pred_custom = out.cpu().numpy().flatten() * scaler.scale_[target_idx] + scaler.mean_[target_idx]\n',
                '\n',
                '# 8. Compare\n',
                'label_custom = pd.read_excel(\"data/label.xlsx\")\n',
                'true_custom = label_custom[\"OT\"].values\n',
                '\n',
                'plt.figure(figsize=(10, 5))\n',
                'plt.plot(true_custom, marker=\"o\", label=\"Ground Truth (label.xlsx)\", color=\"blue\")\n',
                'plt.plot(pred_custom, marker=\"x\", linestyle=\"--\", label=\"Seq2Seq Prediction\", color=\"orange\")\n',
                'plt.title(\"Seq2Seq Evaluation on Custom test_data.xlsx\")\n',
                'plt.legend()\n',
                'plt.grid(True)\n',
                'plt.show()\n',
                '\n',
                'print(f\"Custom Data MAE: {np.mean(np.abs(pred_custom - true_custom)):.4f}\")\n'
            ]

with open(path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

